language: generic
sodu: required
services:
  - docker

before_install:
  - docker build -t xiaohu07/docker-react -f Dockerfile.dev .


script:
  - docker run -e CI=true xiaohu07/docker-react npm run test
